# Generated by Django 3.2 on 2022-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('needed_skills', models.CharField(blank=True, max_length=500, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=1000000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000000, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
