# Generated by Django 4.1.3 on 2022-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200, null=True)),
                ("about_project", models.CharField(max_length=1000, null=True)),
                ("required_skills", models.CharField(max_length=500, null=True)),
                ("bid", models.CharField(max_length=10000, null=True)),
                ("document", models.FileField(null=True, upload_to="document")),
                ("email", models.CharField(max_length=200, null=True)),
                ("phone_no", models.CharField(max_length=13, null=True)),
            ],
        ),
    ]
